# Important link: https://docs.github.com/en/actions/guides/building-and-testing-python

name: Lint Files

on:
  push:
    branches:
      # - master

  pull_request:
    branches:
      - master

jobs:
  Lint-Files:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: pip install flake8

    - name: Run flake8
      run: flake8 .
